using DescriptionAttribute = System.ComponentModel.DescriptionAttribute;


namespace SpecFlowTestProject.Support.Enums
{
    public enum DriversLicenses
    {
        [Description("AU")]
        Australia,
        [Description("CA")]
        Canada,
        [Description("CN")]
        China,
        [Description("DK")]
        Denmark,
        [Description("FR")]
        France,
        [Description("DE")]
        Germany,
        [Description("NL")]
        Netherlands,
        [Description("NZ")]
        NewZealand,
        [Description("SE")]
        Sweden,
        [Description("CH")]
        Switzerland,
        [Description("UK")]
        UnitedKingdom,
        [Description("US")]
        UnitedStatesOfAmerica,
        [Description("AF")]
        Afghanistan,
        [Description("AL")]
        Albania,
        [Description("DZ")]
        Algeria,
        [Description("AS")]
        AmericanSamoa,
        [Description("AD")]
        Andora,
        [Description("AO")]
        Angola,
        [Description("AI")]
        Anguilla,
        [Description("AQ")]
        Antarctica,
        [Description("AG")]
        AntiguaAndBarbados,
        [Description("AR")]
        Argentina,
        [Description("AM")]
        Armenia,
        [Description("AW")]
        Aruba,
        [Description("AT")]
        Austria,
        [Description("AZ")]
        Azerbaijan,
        [Description("BS?")]
        Bahamas,
        [Description("BH")]
        Bahrain,
        [Description("BD")]
        Bangladesh,
        [Description("BB")]
        Barbados,
        [Description("BY")]
        Belarus,
        [Description("BE")]
        Belgium,
        [Description("BZ")]
        Belize,
        [Description("BJ")]
        Benin,
        [Description("BM")]
        Bermuda,
        [Description("BO")]
        Bolivia,
        [Description("BA")]
        BosniaAndHerzegovina,
        [Description("BW")]
        Botswana,
        [Description("BV")]
        BouvetIsland,
        [Description("BR")]
        Brazil,
        [Description("IO")]
        BritishIndianOceanTerritory,
        [Description("BN")]
        Brunei,
        [Description("BG")]
        Bulgaria,
        [Description("BF")]
        BurkinaFaso,
        [Description("BI")]
        Burundi,
        [Description("BT")]
        Butan,
        [Description("KH")]
        Cambodia,
        [Description("CM")]
        Cameroon,
        [Description("CV")]
        CapeVerde,
        [Description("KY")]
        CaymanIslands,
        [Description("CF")]
        CentalAfricanRepublic,
        [Description("TD")]
        Chad,
        [Description("CL")]
        Chile,
        [Description("CX")]
        ChristmasIsland,
        [Description("CC")]
        CocosKeelingIsland,
        [Description("CO")]
        Colombia,
        [Description("KM")]
        Comoros,
        [Description("CG")]
        Congo,
        [Description("CK")]
        CookIsland,
        [Description("CR")]
        CostaRica,
        [Description("CI")]
        CoteDivoire,
        [Description("HR")]
        Croatia,
        [Description("CU")]
        Cuba,
        [Description("CY")]
        Cyprus,
        [Description("CZ")]
        CzechRepublic,
        [Description("DJ")]
        DjiboutiI,
        [Description("DM")]
        Dominica,
        [Description("DO")]
        DominicanRepublic,
        [Description("TP")]
        EastTimor,
        [Description("EC")]
        Ecuador,
        [Description("EG")]
        Egypt,
        [Description("SV")]
        ElSalvador,
        [Description("GQ")]
        EquatorialGuinea,
        [Description("ER")]
        Eritrea,
        [Description("EE")]
        Estonia,
        [Description("ET")]
        Ethiopia,
        [Description("FK")]
        FalklandIslands,
        [Description("FO")]
        FaroeIslands,
        [Description("FJ")]
        Fiji,
        [Description("FI")]
        Finland,
        [Description("FX")]
        FranceMetropolitan,
        [Description("GF")]
        FrenchGuiana,
        [Description("PF")]
        FrenchPolynesia,
        [Description("TF")]
        FrenchSouthernTerritories,
        [Description("GA")]
        Gabon,
        [Description("GM")]
        Gambia,
        [Description("GE")]
        Georgia,
        [Description("GH")]
        Ghana,
        [Description("GI")]
        Gibraltar,
        [Description("GR")]
        Greece,
        [Description("GL")]
        Greenland,
        [Description("GD")]
        Grenada,
        [Description("GP")]
        Guadeloupe,
        [Description("GU")]
        Guam,
        [Description("GT")]
        Guatemala,
        [Description("GN")]
        Guinea,
        [Description("GW")]
        GuineaBissau,
        [Description("GY")]
        Guyana,
        [Description("HT")]
        Haiti,
        [Description("HM")]
        HeardAndMcDonaldIslands,
        [Description("HN")]
        Honduras,
        [Description("HK")]
        HongKong,
        [Description("HU")]
        Hungary,
        [Description("IS")]
        Iceland,
        [Description("IN")]
        India,
        [Description("ID")]
        Indonesia,
        [Description("IR")]
        Iran,
        [Description("IQ")]
        Iraq,
        [Description("IE")]
        Ireland,
        [Description("IL")]
        Israel,
        [Description("IT")]
        Italy,
        [Description("JM")]
        Jamaica,
        [Description("JP")]
        Japan,
        [Description("JO")]
        Jordan,
        [Description("KZ")]
        Kazakhstan,
        [Description("KE")]
        Kenya,
        [Description("KI")]
        Kiribati,
        [Description("KW")]
        Kuwait,
        [Description("KG")]
        Kyrgyzstan,
        [Description("LA")]
        LaoPeoplesDemocraticRepublic,
        [Description("LV")]
        Latvia,
        [Description("LB")]
        Lebanon,
        [Description("LS")]
        Lesotho,
        [Description("LR")]
        Liberia,
        [Description("LY")]
        Libya,
        [Description("LI")]
        Liechtenstein,
        [Description("LT")]
        Lithuania,
        [Description("LU")]
        Luxembourg,
        [Description("MO")]
        Macau,
        [Description("MK")]
        Macedonia,
        [Description("MG")]
        Madagascar,
        [Description("MW")]
        Malawi,
        [Description("MY")]
        Malaysia,
        [Description("MV")]
        Maldives,
        [Description("ML")]
        Mali,
        [Description("MT")]
        Malta,
        [Description("MH")]
        MarshallIslands,
        [Description("MQ")]
        Martinique,
        [Description("MR")]
        Mauritania,
        [Description("MU")]
        Mauritius,
        [Description("YT")]
        Mayotte,
        [Description("MX")]
        Mexico,
        [Description("FM")]
        MicronesiaFederatedStatesOf,
        [Description("MD")]
        Moldova,
        [Description("MC")]
        Monaco,
        [Description("MN")]
        Mongolia,
        [Description("MS")]
        Montserrat,
        [Description("MA")]
        Morocco,
        [Description("MZ")]
        Mozambique,
        [Description("MM")]
        Myanamar,
        [Description("NA")]
        Namibia,
        [Description("NR")]
        Nauru,
        [Description("NP")]
        Nepal,
        [Description("AN")]
        NetherlandsAntilles,
        [Description("NC")]
        NewCaledonia,
        [Description("NI")]
        Nicaragua,
        [Description("NE")]
        Niger,
        [Description("NG")]
        Nigeria,
        [Description("NU")]
        Niue,
        [Description("NF")]
        NorfolkIsland,
        [Description("KP")]
        NorthKorea,
        [Description("MP")]
        NorthernMarianaIslands,
        [Description("NO")]
        Norway,
        [Description("OM")]
        Oman,
        [Description("PK")]
        Pakistan,
        [Description("PW")]
        Palau,
        [Description("PA")]
        Panama,
        [Description("PG")]
        PapuaNewGuinea,
        [Description("PY")]
        Paraguay,
        [Description("PE")]
        Peru,
        [Description("PH")]
        Philippines,
        [Description("PN")]
        PitcairnIslands,
        [Description("PL")]
        Poland,
        [Description("PT")]
        Portugal,
        [Description("PR")]
        PuertoRico,
        [Description("QA")]
        Qatar,
        [Description("RE")]
        Reunion,
        [Description("RO")]
        Romania,
        [Description("RU")]
        RussianFederation,
        [Description("RW")]
        Rwanda,
        [Description("SH")]
        SaintHelena,
        [Description("KN")]
        SaintKittsAndNevis,
        [Description("LC")]
        SaintLucia,
        [Description("PM")]
        SaintPierreAndMiquelon,
        [Description("VC")]
        SaintVincentAndTheGrenadines,
        [Description("WS")]
        Samoa,
        [Description("SM")]
        SanMarino,
        [Description("ST")]
        SaoTomeAndPrincipe,
        [Description("SA")]
        SaudiArabia,
        [Description("SN")]
        Senegal,
        [Description("SC")]
        Seychelles,
        [Description("SG")]
        Singapore,
        [Description("SK")]
        Slovakia,
        [Description("SI")]
        Slovenia,
        [Description("SB")]
        SolomonIslands,
        [Description("SO")]
        Somalia,
        [Description("ZA")]
        SouthAfrica,
        [Description("GS")]
        SouthGeorgia,
        [Description("KR")]
        SouthKorea,
        [Description("ES")]
        Spain,
        [Description("SL")]
        SriLanka,
        [Description("SD")]
        Sudan,
        [Description("SR")]
        Suriname,
        [Description("SJ")]
        SvalbardandJanMayenIslands,
        [Description("SY")]
        Syria,
        [Description("TI")]
        Tahiti,
        [Description("TW")]
        Taiwan,
        [Description("TJ")]
        Tajikistan,
        [Description("TZ")]
        Tanzania,
        [Description("TH")]
        Thailand,
        [Description("TG")]
        Togo,
        [Description("TK")]
        Tokelau,
        [Description("TO")]
        Tonga,
        [Description("TT")]
        TrinidadAndTobago,
        [Description("TN")]
        Tunisia,
        [Description("TR")]
        Turkey,
        [Description("TM")]
        Turkmenistan,
        [Description("TC")]
        TurksAndCaicosIslands,
        [Description("TV")]
        Tuvalu,
        [Description("UG")]
        Uganda,
        [Description("UA")]
        Ukraine,
        [Description("AE")]
        UnitedArabEmirates,
        [Description("UY")]
        Uruguay,
        [Description("UM")]
        USMinorOutlyingIslands,
        [Description("UZ")]
        Uzbekistan,
        [Description("VU")]
        Vanuatu,
        [Description("VA")]
        VaticanCity,
        [Description("VE")]
        Venezuala,
        [Description("VN")]
        Vietnam,
        [Description("VG")]
        VirginIslandsGB,
        [Description("VI")]
        VirginIslandsUS,
        [Description("WF")]
        WallisAndFutunaIslands,
        [Description("EH")]
        WesternSahara,
        [Description("YE")]
        Yemen,
        [Description("YU")]
        Yugoslavia,
        [Description("ZR")]
        Zaire,
        [Description("ZM")]
        Zambia,
        [Description("ZW")]
        Zimbabwe
    }
}
